title: KHE Homelab
theme: dark
color: zinc
headerStyle: clean
useEqualHeights: true
layout:
  Pilv:
    style: row
    columns: 3
  Meedia:
    style: row
    columns: 3
  AI:
    style: row
    columns: 3
  Infra:
    style: row
    columns: 3
