title: KHE Homelab
favicon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/heimdall.png
theme: dark
color: zinc
headerStyle: clean
cardBlur: md
useEqualHeights: true
layout:
  Pilv:
    style: row
    columns: 3
  Meedia:
    style: row
    columns: 3
  AI:
    style: row
    columns: 3
  Virtualisatsioon:
    style: row
    columns: 2
  Haldus:
    style: row
    columns: 3
