title: KHE Homelab
theme: dark
color: zinc
headerStyle: underlined
useEqualHeights: true
layout:
  Igapäev:
    style: row
    columns: 4
  Veeb:
    style: row
    columns: 4
  Infra:
    style: row
    columns: 3
