- resources:
    label: Docker VM
    cpu: true
    memory: true
    disk: /srv
    cacheInterval: 10
    expanded: true

- greeting:
    text_size: xl
    text: KHE Homelab

- datetime:
    text_size: l
    format:
      dateStyle: long
      timeStyle: short
      hour12: false

- search:
    provider: google
    target: _blank
