- greeting:
    text_size: xl
    text: KHE Homelab

- datetime:
    text_size: l
    format:
      dateStyle: long
      timeStyle: short
      hour12: false

- openmeteo:
    label: Tallinn
    latitude: 59.437
    longitude: 24.7536
    timezone: Europe/Tallinn
    units: metric
    cache: 15

- resources:
    label: Docker VM
    cpu: true
    memory: true
    cacheInterval: 10
    expanded: true

- resources:
    label: ZFS pool (/srv)
    disk: /srv
    expanded: true

- search:
    provider: google
    target: _blank
