services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.33.1@sha256:a4a5841bba093d81e5f4ad1eaedb4da3fda6dbb2528c552349da50ad1f7ae708
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"
    environment:
      - TZ=Europe/Tallinn
    volumes:
      - ${AUDIOBOOKS_PATH}:/audiobooks
      - ${PODCASTS_PATH}:/podcasts
      - audiobookshelf_config:/config
      - audiobookshelf_metadata:/metadata
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  audiobookshelf_config:
  audiobookshelf_metadata:

networks:
  proxy:
    external: true
