services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.33.2@sha256:a44ed89b3e845faa1f7d353f2cc89b2fcd8011737dd14075fa963cf9468da3a5
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"
    environment:
      - TZ=Europe/Tallinn
    volumes:
      - ${AUDIOBOOKS_PATH}:/audiobooks
      - ${PODCASTS_PATH}:/podcasts
      - audiobookshelf_config:/config
      - audiobookshelf_metadata:/metadata
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  audiobookshelf_config:
  audiobookshelf_metadata:

networks:
  proxy:
    external: true
