services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.35.0@sha256:89276ff2e0b3d2f07dd334b641f27a34ab7f02e1047c60b7b8a30126cb0813a5
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"
    environment:
      - TZ=Europe/Tallinn
    volumes:
      - ${AUDIOBOOKS_PATH}:/audiobooks
      - ${PODCASTS_PATH}:/podcasts
      - audiobookshelf_config:/config
      - audiobookshelf_metadata:/metadata
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '1.00'

volumes:
  audiobookshelf_config:
  audiobookshelf_metadata:

networks:
  proxy:
    external: true
